"""
Refresh the local Arabic ECU knowledge cache.

Runtime never fetches the web. This setup command crawls polite ECU Arabic pages
only, skips media/PDF assets, and writes data/ecu_knowledge_ar.json.
"""

from __future__ import annotations

import json
import sys
import time
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://ecu.edu.eg/ar/"
OUTPUT_PATH = Path("data/ecu_knowledge_ar.json")
MAX_PAGES = 40
REQUEST_DELAY_SEC = 1.5
SKIP_SUFFIXES = (".pdf", ".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".zip", ".doc", ".docx", ".xls", ".xlsx")


def main() -> int:
    if OUTPUT_PATH.exists() and "--force" not in sys.argv:
        print(f"[SKIPPED] {OUTPUT_PATH} already exists. Use --force to refresh.")
        return 0

    session = requests.Session()
    queue: deque[str] = deque([BASE_URL])
    seen: set[str] = set()
    entries: list[dict] = []

    while queue and len(seen) < MAX_PAGES:
        url = queue.popleft()
        if url in seen or not _is_allowed_url(url):
            continue
        seen.add(url)
        try:
            response = session.get(url, timeout=12, headers={"User-Agent": "NavigatorECUArabicCache/1.0"})
            response.raise_for_status()
        except Exception as exc:
            print(f"[FAILED] {url} {exc}")
            continue

        soup = BeautifulSoup(response.text, "html.parser")
        entry = _entry_from_page(url, soup)
        if entry:
            entries.append(entry)
            print(f"[SCRAPED] {url}")

        for link in soup.find_all("a", href=True):
            next_url = urljoin(url, link["href"]).split("#", 1)[0]
            if next_url not in seen and _is_allowed_url(next_url):
                queue.append(next_url)
        time.sleep(REQUEST_DELAY_SEC)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "base_url": BASE_URL,
        "entry_count": len(entries),
        "note": "Arabic ECU cache generated by scripts/scrape_ecu_arabic.py",
        "entries": entries,
    }
    OUTPUT_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[DONE] {len(entries)} Arabic ECU entries written to {OUTPUT_PATH}")
    return 0


def _is_allowed_url(url: str) -> bool:
    parsed = urlparse(url)
    if parsed.netloc and parsed.netloc.lower() != "ecu.edu.eg":
        return False
    if not parsed.path.startswith("/ar"):
        return False
    return not parsed.path.lower().endswith(SKIP_SUFFIXES)


def _entry_from_page(url: str, soup: BeautifulSoup) -> dict | None:
    for tag in soup(["script", "style", "nav", "footer"]):
        tag.decompose()
    title = " ".join((soup.title.string if soup.title and soup.title.string else "").split())
    content = " ".join(soup.get_text(" ").split())
    if len(content) < 80:
        return None
    keywords = _keywords_for(title, content)
    return {
        "title": title or url,
        "url": url,
        "content": content[:900],
        "keywords": keywords,
        "category": _category_for(url, title),
        "lang": "ar",
    }


def _keywords_for(title: str, content: str) -> list[str]:
    seeds = [title]
    for word in ("هندسة", "حاسبات", "صيدلة", "علاج طبيعي", "فنون", "تصميم", "مكتبة", "شؤون الطلاب", "بوابة الطالب"):
        if word in content:
            seeds.append(word)
    return [seed for seed in dict.fromkeys(" ".join(seed.split()) for seed in seeds) if seed]


def _category_for(url: str, title: str) -> str:
    lowered = f"{url} {title}".lower()
    if "facult" in lowered or "كلية" in title:
        return "faculty"
    if "contact" in lowered:
        return "contact"
    if "library" in lowered or "مكتبة" in title:
        return "library"
    return "general"


if __name__ == "__main__":
    raise SystemExit(main())
